# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.11
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: npm install
      - run: npm run build:github

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - docs/.vuepress/dist
  
  deploy-to-github:
    docker:
      - image: circleci/node:9.11
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: git config credential.helper 'cache --timeout=120'
      - run: git config --global user.email hbobenicio@gmail.com
      - run: git config --global user.name "Hugo Benício (CircleCI)"
      - run: npm run publish:github

workflows:
  version: 2
  pipeline:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages
      - deploy-to-github:
          requires:
            - build
          filters:
            branches:
              ignore: gh-pages
